name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `master` branch
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Run CI checks first
  ci:
    # Skip CI if the commit message contains [skip ci]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    uses: ./.github/workflows/ci.yml

  build:
    needs: ci
    # Always run build step, even if CI was skipped
    if: always() && (needs.ci.result == 'success' || needs.ci.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          # Fetch the latest changes in case CI pushed formatting changes
          ref: master
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          node-version: 18

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
